### ISSUE TITLE
помилки при відображенні нових назв на сайті

### ISSUE THREAD

**Issue by ujeen2010** [deivan/rename.dp.ua#18]
Доброго дня!
Дякую за Вашу працю в створенні корисного ресурсу.
Виявилось некоректне відображення нових назв вулиць міста - на нову накладається інший текст (якщо є два і більше варіантів результатів пошуку) або взагалі нова назва не відображується (якщо варіант пошуку один).
До речі, є помилка у назві: вул. ВойцеховИч
![prntscr](https://cloud.githubusercontent.com/assets/17591695/13488193/5f681280-e128-11e5-8afd-f95a78966941.png)
![-2 prntscr](https://cloud.githubusercontent.com/assets/17591695/13488194/5f68e8a4-e128-11e5-9b99-716e9ac3af9f.png)

а (не Войцеховіча).

Прошу виправити.
Ще раз висловлюю подяку за Вашу працю! До речі, пошта на info@rename.dp.ua не доставляється.

**Comment by deivan** [comment]
Дивлячись на скріншот я бачу, що у вас старий варіант пошуку, - вже кілька тижднів функціонує новій. Мабуть, у вас в кеші сайт застряг, спробуйте примусово обновити сторінку - контрол + Ф5.
Пошту буду штовхати. Дякую за увагу до проекту.

**Comment by ujeen2010** [comment]
Дякую, допомогло! 

03 березня 2016, 12:37:10, від "ivan" < notifications@github.com >: 

Дивлячись на скріншот я бачу, що у вас старий варіант пошуку, - вже кілька тижднів функціонує новій. Мабуть, у вас в кеші сайт застряг, спробуйте примусово обновити сторінку - контрол + Ф5. 
Пошту буду штовхати. Дякую за увагу до проекту. — 
Reply to this email directly or view it on GitHub . 

## 

Євген Базюкевич 
Правові послуги 

Baziukevych Ievgen 
Legal Services 

+38 067-634-44-13 
amparo@ukr.net
