### ISSUE TITLE
API data versioning

### ISSUE THREAD

**Issue by Den-Rimus** [deivan/rename.dp.ua#8]
Снова привет!

Нельзя ли добавить еще один вызов API, вроде
GET
/last_update_timestamp.json

который бы возвращал timestamp последнего апдейта - чтоб сверять с локально закешированным и не качать при каждом запуске (речь идет в первую очередь о мобильном клиенте, конечно)?

**Comment by deivan** [comment]
годное замечание! как насчет дополнительного поля last_update в корне глобального объекта? ведь это все же проще будет, чем еще один гет-запрос городить?..

**Comment by deivan** [comment]
добавлено поле lastUpdate с целым числом вида Unix timestamp для версирования

**Comment by Den-Rimus** [comment]
Не совсем понимаю, чем это поможет...

Идея была - не качать весь json с переименованными объектами без надобности. Теперь получается, что его всё равно надо скачать весь, но можно попользоваться (если данные обновлялись) или нет. Польза сомнительна

**Comment by deivan** [comment]
ок, добавил в корень last_data_update.json
